development:
  initial_credits: 10000
  initial_turns: 300
  initial_fighters: 100
  initial_exp: 0
  initial_holds: 20
  initial_colonists: 100
  initial_ore: 10000
  initial_equipment: 20000
  initial_organics: 50000
  initial_colonists: 1000
  planet_types: ["M", "K", "O", "L", "C", "H", "U"]
  planet_ratio: 0.1
  initial_sector: 1
test:
  initial_credits: 10000
  initial_turns: 300
  initial_fighters: 100
  initial_exp: 0
  initial_holds: 20
  initial_colonists: 100
  initial_ore: 10000
  initial_equipment: 20000
  initial_organics: 50000
  initial_colonists: 1000
  planet_types: ["M", "K", "O", "L", "C", "H", "U"]
  planet_ratio: 0.8
  initial_sector: 1
